import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "../styles/style.css";
import { ReduxProvider } from "@/components/additional/CustomReduxProvider";
import Header from "@/components/main/Header";
import BurgerMenue from "@/components/main/BurgerMenue";

const montserrat = Montserrat({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Аккамуляторы Сочи",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased`}>
        <ReduxProvider>
          <Header />
          {children}
          <BurgerMenue />
        </ReduxProvider>
      </body>
    </html>
  );
}
